"""initial schema

Revision ID: d48cee59fb24
Revises: 
Create Date: 2026-08-13 13:16:21.970555

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd48cee59fb24'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blobs',
    sa.Column('blob_name', sa.String(length=64), nullable=False),
    sa.Column('path', sa.String(length=1024), nullable=False),
    sa.Column('content_size', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=32), nullable=True),
    sa.Column('file_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('blob_name')
    )
    op.create_index('ix_blobs_language', 'blobs', ['language'], unique=False)
    op.create_index('ix_blobs_last_seen', 'blobs', ['last_seen'], unique=False)
    op.create_index('ix_blobs_retry_count', 'blobs', ['retry_count'], unique=False)
    op.create_index('ix_blobs_status', 'blobs', ['status'], unique=False)
    op.create_table('chains',
    sa.Column('chain_id', sa.String(length=64), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('total_blobs', sa.Integer(), nullable=False),
    sa.Column('total_chunks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('chain_id')
    )
    op.create_index('ix_chains_updated_at', 'chains', ['updated_at'], unique=False)
    op.create_table('chunks',
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_size', sa.Integer(), nullable=False),
    sa.Column('chunk_type', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('embedded', sa.Boolean(), server_default='false', nullable=False),
    sa.PrimaryKeyConstraint('content_hash')
    )
    op.create_index('ix_chunks_chunk_type', 'chunks', ['chunk_type'], unique=False)
    op.create_index('ix_chunks_embedded', 'chunks', ['embedded'], unique=False)
    op.create_table('embedding_providers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=128), nullable=False),
    sa.Column('embed_endpoint', sa.String(length=512), nullable=True),
    sa.Column('embed_model', sa.String(length=128), nullable=True),
    sa.Column('rerank_endpoint', sa.String(length=512), nullable=True),
    sa.Column('rerank_model', sa.String(length=128), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('max_batch_size', sa.Integer(), nullable=False),
    sa.Column('max_batch_chars', sa.Integer(), nullable=False),
    sa.Column('max_input_chars', sa.Integer(), nullable=False),
    sa.Column('input_overlap_chars', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('blob_chunks',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('blob_name', sa.String(length=64), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('start_line', sa.Integer(), nullable=False),
    sa.Column('end_line', sa.Integer(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['blob_name'], ['blobs.blob_name'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['content_hash'], ['chunks.content_hash'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('blob_name', 'content_hash', 'start_line', 'end_line', name='uq_blob_chunks_span')
    )
    op.create_index('ix_blob_chunks_blob_index', 'blob_chunks', ['blob_name', 'chunk_index'], unique=False)
    op.create_index('ix_blob_chunks_blob_name', 'blob_chunks', ['blob_name'], unique=False)
    op.create_index('ix_blob_chunks_content_hash', 'blob_chunks', ['content_hash'], unique=False)
    op.create_table('blob_staging',
    sa.Column('blob_name', sa.String(length=64), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['blob_name'], ['blobs.blob_name'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('blob_name')
    )
    op.create_index('ix_blob_staging_created_at', 'blob_staging', ['created_at'], unique=False)
    op.create_table('chain_members',
    sa.Column('chain_id', sa.String(length=64), nullable=False),
    sa.Column('blob_name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['chain_id'], ['chains.chain_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chain_id', 'blob_name')
    )
    op.create_index('ix_chain_members_blob_name', 'chain_members', ['blob_name'], unique=False)
    op.create_table('embedding_credentials',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('provider_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('api_key', sa.String(length=512), nullable=False),
    sa.Column('api_key_hash', sa.String(length=64), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('max_batch_size', sa.Integer(), nullable=True),
    sa.Column('max_batch_chars', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('rate_limit', sa.Integer(), nullable=True),
    sa.Column('timeout_seconds', sa.Integer(), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.func.now(), nullable=False),
    sa.ForeignKeyConstraint(['provider_id'], ['embedding_providers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('api_key_hash')
    )
    op.create_index('idx_embedding_credentials_priority', 'embedding_credentials', ['priority'], unique=False)
    op.create_index('idx_embedding_credentials_provider_id', 'embedding_credentials', ['provider_id'], unique=False)
    op.create_index('idx_embedding_credentials_status', 'embedding_credentials', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_embedding_credentials_status', table_name='embedding_credentials')
    op.drop_index('idx_embedding_credentials_provider_id', table_name='embedding_credentials')
    op.drop_index('idx_embedding_credentials_priority', table_name='embedding_credentials')
    op.drop_table('embedding_credentials')
    op.drop_index('ix_chain_members_blob_name', table_name='chain_members')
    op.drop_table('chain_members')
    op.drop_index('ix_blob_staging_created_at', table_name='blob_staging')
    op.drop_table('blob_staging')
    op.drop_index('ix_blob_chunks_content_hash', table_name='blob_chunks')
    op.drop_index('ix_blob_chunks_blob_name', table_name='blob_chunks')
    op.drop_index('ix_blob_chunks_blob_index', table_name='blob_chunks')
    op.drop_table('blob_chunks')
    op.drop_table('embedding_providers')
    op.drop_index('ix_chunks_chunk_type', table_name='chunks')
    op.drop_table('chunks')
    op.drop_index('ix_chains_updated_at', table_name='chains')
    op.drop_table('chains')
    op.drop_index('ix_blobs_status', table_name='blobs')
    op.drop_index('ix_blobs_retry_count', table_name='blobs')
    op.drop_index('ix_blobs_last_seen', table_name='blobs')
    op.drop_index('ix_blobs_language', table_name='blobs')
    op.drop_table('blobs')
    # ### end Alembic commands ###
