"""领域仓储协议(由 infrastructure/persistence 提供实现)。"""

from __future__ import annotations

from typing import TYPE_CHECKING, Protocol, Sequence

if TYPE_CHECKING:
    from oce.domain.blob.blob import Blob
    from oce.domain.chain.chain import Chain
    from oce.domain.chunk import Chunk, LocatedChunk


class BlobRepository(Protocol):
    async def get(self, blob_name: str) -> Blob | None: ...

    async def get_many(self, blob_names: Sequence[str]) -> dict[str, Blob]: ...

    async def exists(self, blob_name: str) -> bool: ...

    async def exists_many(self, blob_names: Sequence[str]) -> dict[str, bool]: ...

    async def save(self, blob: Blob) -> None: ...

    async def save_many(self, blobs: Sequence[Blob]) -> None: ...

    async def delete(self, blob_name: str) -> None: ...

    async def delete_many(self, blob_names: Sequence[str]) -> None: ...

    async def find_pending(self, blob_names: Sequence[str] | None = None) -> list[Blob]: ...

    async def list_pending_names(self) -> list[str]:
        """全部 pending blob 的名字。只取标识，不组装聚合。"""
        ...

    async def find_expired(self, ttl_days: int, batch_size: int = 1000) -> list[str]: ...

    async def touch_last_seen(self, blob_names: Sequence[str]) -> None: ...

    # blob_staging 操作（worker 消费用原文缓冲区）
    async def get_staging(self, blob_name: str) -> str | None: ...
    async def save_staging(self, blob_name: str, content: str) -> None: ...
    async def delete_staging(self, blob_name: str) -> None: ...

    async def get_paths(
        self,
        blob_names: Sequence[str],
        limit: int | None = None,
    ) -> list[str]: ...

    async def count_paths(self, blob_names: Sequence[str]) -> int: ...

    async def get_path_blob_pairs(
        self,
        blob_names: Sequence[str],
    ) -> list[tuple[str, str]]: ...

    async def get_blob_contents(
        self,
        blob_names: Sequence[str],
    ) -> dict[str, tuple[str, str]]: ...

    async def find_stale_with_staging(
        self,
        stale_hours: int = 24,
        limit: int = 100,
    ) -> list[str]:
        """查找有 staging 但长时间未处理的 pending blob(用于重新入队或清理)"""
        ...


class ChainRepository(Protocol):
    async def get(self, chain_id: str) -> Chain | None: ...

    async def exists(self, chain_id: str) -> bool: ...

    async def create(self, members: Sequence[str]) -> Chain: ...

    async def get_members(self, chain_id: str) -> set[str]: ...

    async def apply_checkpoint(
        self,
        chain_id: str,
        added: Sequence[str],
        deleted: Sequence[str],
    ) -> int | None: ...

    async def touch_members(self, chain_id: str) -> None: ...

    async def delete(self, chain_id: str) -> None: ...

    async def find_expired(self, ttl_days: int) -> list[str]: ...


class ChunkRepository(Protocol):
    async def get(self, content_hash: str) -> Chunk | None: ...

    async def get_many(self, content_hashes: Sequence[str]) -> dict[str, Chunk]: ...

    async def save(self, chunk: Chunk) -> None: ...

    async def save_many(self, chunks: Sequence[Chunk]) -> None: ...

    async def mark_embedded(self, content_hashes: Sequence[str]) -> None: ...

    async def find_pending_for_blobs(
        self,
        blob_names: Sequence[str],
        limit: int | None = None,
    ) -> list[LocatedChunk]: ...
